// <auto-generated />
namespace ShoppingList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddAddressID_In_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAddressID_In_User));
        
        string IMigrationMetadata.Id
        {
            get { return "202009241248340_AddAddressID_In_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
